#!/usr/bin/env php
<?php

use Flytachi\Winter\Thread\Runnable;

// initialization
$fileAutoloader = dirname(__DIR__, 2) . '/autoload.php';
if (file_exists($fileAutoloader)) {
    require_once $fileAutoloader;
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}


// 1. Command line options (debugging, configure)
$options = getopt('', ['namespace::', 'name::', 'tag::', 'debug']);

// Debugging / Configure
set_time_limit(0);
ob_implicit_flush();
ignore_user_abort(true);

if (isset($options['debug'])) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
    ini_set('display_startup_errors', 0);
}


// 2. Reading all standard input data (stdin).
$payload = stream_get_contents(STDIN);

if (empty($payload)) {
    fwrite(STDERR, "Error: No payload received from stdin.\n");
    exit(1);
}

// 3. Decode and deserialize the object Runnable.
if (function_exists('\Opis\Closure\serialize')) {
    $runnable = \Opis\Closure\unserialize(
        $payload,
        \Flytachi\Winter\Thread\Thread::getSerSecurity()
    );
} else {
    $runnable = unserialize($payload);
}
unset($payload);

if (!$runnable instanceof Runnable) {
    fwrite(STDERR, "Error: The provided payload is not a valid RunnableInterface object.\n");
    exit(1);
}


// 4. Set the process title.
if (function_exists('cli_set_process_title')) {
    $processNamespace = isset($options['namespace'])
        ? ($options['namespace'] . ' ') : '';
    $processTag = $options['tag'] ?? 'runnable';

    // Name
    if (isset($options['name'])) {
        $processName = $options['name'];
    } else {
        $className = get_class($runnable);
        $processName = substr($className, strrpos($className, '\\') + 1);
    }

    cli_set_process_title("WinterThread {$processNamespace}-> {$processName}@$processTag");
    unset($processNamespace, $processTag, $processName);
}

// 5. Let's complete the task.
try {

    // Custom args
    $rawOptions = getopt('', ['arg-::']);
    $customArgs = [];
    if (isset($rawOptions['arg-'])) {
        $args = is_array($rawOptions['arg-']) ? $rawOptions['arg-'] : [$rawOptions['arg-']];
        foreach ($args as $arg) {
            if (str_contains($arg, '=')) {
                list($key, $value) = explode('=', $arg, 2);
                $customArgs[$key] = $value;
            } else {
                $customArgs[$arg] = true;
            }
        }
    }

    $runnable->run($customArgs);
    exit(0);
} catch (\Throwable $e) {
    fwrite(STDERR, "Uncaught exception in background process: " . $e->getMessage() . "\n");
    fwrite(STDERR, $e->getTraceAsString() . "\n");
    exit(1);
}
